name: tensorflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.13
  - pip=22.0.4
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - pip:
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - scikit-learn
    - tensorflow
    - mlflow
    - pylint